### ISSUE TITLE
Demo Database in RC3

### ISSUE THREAD

**Issue by windgaucho** [OpenNTF/org.openntf.domino#135]
Hi I've just installed the API y designer and create a Demo database from the on disk project of the demo database shipped with this release.

I get errors of missing classes on:

org.openntf.domino.xots.XotsAbstractScheduledTasklet 
org.openntf.domino.xots.XotsBaseTasklet 
org.openntf.domino.xots.XotsDaemon 
org.openntf.arpa.NamePartsMap.Key

Am I missing something?

**Comment by paulswithers** [comment]
I don't think so. Xots was still quite heavily in development at the time and has since been quite considerably reorganised. It looks like the NamePartsMap.Key enum got moved to org.openntf.domino.ext.Name.NamePartKey prior to the release. The classes with the errors can be deleted - the Xots functionality now works as in these blog posts http://www.intec.co.uk/tag/xots/ and a separate NameODA class has been added.

We're hoping to have a new release out shortly and I'll make sure the demo database is included and working fully.

**Comment by windgaucho** [comment]
Tanks you Mr. Withers for your answer! I am a very little experience with the openntf domino api.
I will try to fix the org.openntf.domino.ext.Name.NamePartKey errors, anyway I can open the database and wath all the example code. It's of a great help to my in order to learn the api!
I will be wating for the next release!

Thanks you very much.
